#!/bin/bash

echo "Deleting previous test from Testing"
rm -rf /var/www/testing
mkdir -p /var/www/testing

echo "Moving files to Testing"
cp /root/tmp/bb-worker/worker/runtests/build/*.html    /var/www/testing
cp /root/tmp/bb-worker/worker/runtests/build/*.php     /var/www/testing
cp /root/tmp/bb-worker/worker/runtests/build/.htaccess /var/www/testing

echo "Re-owning files"
touch /var/www/testing/output.tab
chown -R apache. /var/www/testing

echo "Reseting MMW Testing databases"
echo $MSQL_UNAME
echo $MSQL_PASS
#mysqld --user=$MSQL_UNAME --password=$MSQL_PASS < resetDB.sql > /var/www/testing/output.tab

echo "Finished!"
exit 0
